config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  get 'tasks', to: 'task#index'
  get 'tasks/create', to: 'task#create'
  get 'tasks/:id', to: 'task#show', as: :task
  post 'tasks', to: 'task#new'
  get 'tasks/:id/edit', to: 'task#edit', as: :edit_task
  patch 'tasks/:id', to: 'task#update'
  delete 'tasks/:id', to: 'task#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/task_controller.rb
class TaskController < ApplicationController

  def index
    @tasks = Task.all
  end

  def create
    @task = Task.new
  end

  def show
    @task = Task.find(params[:id])
  end

  def edit
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new(task_params)
    @task.save
    redirect_to tasks_path
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    # No need for app/views/restaurants/destroy.html.erb
    redirect_to tasks_path, status: :see_other
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/task/create.html.erb
<h1>Create a task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.submit %>
<% end %>
<br>
<%= link_to "Back to list", tasks_path%>

app/views/task/edit.html.erb
<h1>Edit Task</h1>

<%= form_with model: @task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed, "Mark as completed" %>
  <%= f.check_box :completed %>

  <%= f.submit %>
<% end %>

<%= link_to "Back to list", tasks_path%>

app/views/task/index.html.erb
<h1>My Tasks</h1>

<ul>
  <% @tasks.each do |task| %>
    <li><%= link_to task.title, task_path(task) %>
    - <%= task.completed ? "✓" : "X" %>
     / <%= link_to "Delete", task_path(task),
    data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
    %></li>
  <% end %>
</ul>

<%= link_to 'Create Task', tasks_create_path %>

app/views/task/show.html.erb
<h2><%= @task.title %></h2>
<p><%= @task.details %></p>
<% if @task.completed == true %>
<p>Task completed? <%= "✓"%></p>
<% else %>
<p>Task completed? <%= "X"%></p>
<% end %>

<br>

<%= link_to "Back to list", tasks_path%>

<%= link_to "Edit Task", edit_task_path%>

<%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
%>